### ISSUE TITLE
Unable to create new entity with relation

### ISSUE THREAD

**Issue by joerivanarkel** [joerivanarkel/Blazor-SQL-Database#12]
When creating a new entity with a object with id attached, it returns the following error. 
 _Cannot insert explicit value for identity column in table 'Persons' when IDENTITY_INSERT is set to OFF_

**Comment by teusvanarkel** [comment]
Problem was the detached state of the entity. When passing data from the API to Blazor over the httprequest the entity loses its attachedstate. When a create method is made with a new entity but one of the properties are an excisting entity. The state of that excisting entity is detached. It must be attached again.
This is solved in the repository: cityrepository:
https://github.com/joerivanarkel/Blazor-SQL-Database/blob/UI-Pages-creation/Data/Repositories/CityRepository.cs
